apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: thangcoi123
  DB_HOST: host.docker.internal
  OLLAMA_API_URL: http://ollama:11434
  CHROMA_PATH: chroma_store
  EMBEDDING_MODEL_NAME: intfloat/multilingual-e5-small
  LLM_MODEL: llama3:latest
  CSV_FILE_PATH: /app/data/metadata__.csv
  DATAMODEL_PATH: /app/data/datamodel.json
  META_STORAGE: postgres
  VECTOR_MODE: update
